module.exports = [
    { name: 'test', previewSrc: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg', src: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg' },
    { name: 'test', previewSrc: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg', src: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg' },
    { name: 'test', previewSrc: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg', src: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg' },
    { name: 'test', previewSrc: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg', src: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg' },
    { name: 'test', previewSrc: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg', src: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg' },
    { name: 'test', previewSrc: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg', src: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg' },
    { name: 'test', previewSrc: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg', src: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg' },
    { name: 'test', previewSrc: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg', src: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg' },
    { name: 'test', previewSrc: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg', src: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg' },
    { name: 'test', previewSrc: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg', src: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg' },
    { name: 'test', previewSrc: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg', src: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg' },
    { name: 'test', previewSrc: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg', src: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg' },
    { name: 'test', previewSrc: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg', src: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg' },
    { name: 'test', previewSrc: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg', src: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg' },
    { name: 'test', previewSrc: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg', src: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg' },
    { name: 'test', previewSrc: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg', src: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg' },
    { name: 'test', previewSrc: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg', src: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg' },
    { name: 'test', previewSrc: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg', src: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg' },
    { name: 'test', previewSrc: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg', src: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg' },
    { name: 'test', previewSrc: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg', src: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg' },
    { name: 'test', previewSrc: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg', src: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg' },
    { name: 'test', previewSrc: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg', src: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg' },
    { name: 'test', previewSrc: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg', src: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg' },
    { name: 'test', previewSrc: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg', src: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg' },
    { name: 'test', previewSrc: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg', src: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg' },
    { name: 'test', previewSrc: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg', src: 'http://www.mlkn.tech/content/pictures/previews/wave.jpg' }
];